baseURL = "https://entreprises-positives.org/"
disableKinds = ["taxonomyTerm"]
languageCode = "fr-FR"
theme = "entreprises-positives"
title = "Entreprises Positives"
[mediaTypes."application/redirect"]
"menu.about" = []
suffixes = ["redirect"]
[[menu.site]]
name = "Sitemap "
weight = 1
[[menu.social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/"
weight = 2
[[menu.social]]
identifier = "facebook"
name = "Facebook"
url = "https://www.facebook.com/"
weight = 1
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true
[outputFormats.redirect]
mediaType = "application/redirect"
notAlternative = true
[sitemap]
filename = "sitemap.xml"
[taxonomies]
financialinvest = "investissement-financier"
humaninvest = "investissement-humain"
maturity = "maturite"
nature = "nature-de-l-impact"
