---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: heading
  label: Global Configuration
- type: document
  path: data/socialshare.yml
  label: Social share
- type: document
  path: data/image.yml
  label: Image size
- type: document
  path: data/cta.yml
  label: Header/Footer HST
- type: document
  path: data/hreflang.yml
  label: hreflang links
- type: document
  path: data/cookie.yml
  label: Cookie banner
- type: document
  path: data/footer.yml
  label: Footer
- type: document
  path: data/date.yml
  label: Date
- type: document
  path: data/notfound.yml
  label: '404'
- type: document
  path: data/authors.yml
  label: Authors
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: dist
  install_dependencies_command: npm run forestry:install
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d dist --baseURL https://omco96khme-kja.instant.forestry.io --appendPort=false
    --disableLiveReload
version: '0.53'
