---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: ''
sections:
- type: heading
  label: Content Page
- type: document
  path: help/README-PAGE.md
  label: Help
  read_only: true
- type: document
  path: content/_index.md
  label: Home page
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{blog/**/*,blogs/**/*,signup/**/*,galerie/**/*,galeries/**/*,redirect/**/*,uploads/**/*}"
  templates:
  - page-entonnoir
  - page-blocs-personalisee
  - page-de-contenu
- type: directory
  path: content/signup
  label: Signup
  create: documents
  match: "**/*"
  templates:
  - page-blocs-personalisee
  - page-entonnoir
- type: heading
  label: Blog
- type: document
  path: help/README-BLOG.md
  label: Help
  read_only: true
- type: document
  path: content/blog/_index.md
  label: List
- type: directory
  path: content/blogs
  label: Blog - Categories
  create: none
  match: "**/*"
  templates:
  - categorie-blog
- type: directory
  path: content/blog
  label: Articles
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - article-bloc-blog
- type: heading
  label: Galery
- type: document
  path: help/README-GALERY.md
  label: Help
  read_only: true
- type: document
  path: content/galerie/_index.md
  label: List
- type: directory
  path: content/galeries
  label: Galery - Category
  create: none
  match: "**/*"
  templates:
  - categorie-galerie
- type: directory
  path: content/galerie
  label: Images
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - image-de-la-galerie
- type: heading
  label: Url & Seo
- type: directory
  path: content/redirect
  label: Redirect
  create: documents
  match: "**/*"
  templates:
  - redirection
- type: heading
  label: Global Configuration
- type: document
  path: help/README-DATA.md
  label: Help
  read_only: true
- type: document
  path: data/socialshare.yml
  label: Social share
- type: document
  path: data/image.yml
  label: Image size
- type: document
  path: data/cta.yml
  label: Header/Footer HST
- type: document
  path: data/hreflang.yml
  label: hreflang links
- type: document
  path: data/cookie.yml
  label: Cookie banner
- type: document
  path: data/footer.yml
  label: Footer
- type: document
  path: data/date.yml
  label: Date
- type: document
  path: data/notfound.yml
  label: '404'
- type: document
  path: data/authors.yml
  label: Authors
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  preview_output_directory: dist
  install_dependencies_command: npm run forestry:install
  preview_docker_image: forestryio/hugo:node12
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d dist --baseURL https://omco96khme-kja.instant.forestry.io --appendPort=false
    --disableLiveReload
version: '0.53'
